import { BYE_BY_TEAM } from "./bye-weeks";
import type { Injury, Player, Position } from "./types";

type Meta = {
  team: string;
  pos: Position;
  adp: number;
  proj: number;
  dsValue?: number;
  injury?: Injury;
  note?: string;
  tags?: string[];
};

/**
 * Snapshot compiled Sept 1, 2026 from public FantasyPros ECR/ADP
 * and DraftSharks PPR 3D ranks/projections. Not an official export.
 * Use the import box to overlay your own latest sheets.
 */
const META: Record<string, Meta> = {
  "Jahmyr Gibbs": {
    team: "DET",
    pos: "RB",
    adp: 1,
    proj: 359,
    dsValue: 100,
    tags: ["elite"],
    note: "DS 3D #1. Workhorse in a top offense — default 1.01.",
  },
  "Puka Nacua": {
    team: "LAR",
    pos: "WR",
    adp: 6,
    proj: 356,
    dsValue: 98,
    tags: ["elite", "ds-boost"],
    note: "DraftSharks' PPR WR1 (180+ targets). Often falls behind Gibbs/Bijan/Chase.",
  },
  "Ja'Marr Chase": {
    team: "CIN",
    pos: "WR",
    adp: 3,
    proj: 339,
    dsValue: 96,
    tags: ["elite", "fp-boost"],
    note: "FantasyPros ECR #1 on Sept 1. Take him if you don't want the RB volatility.",
  },
  "Bijan Robinson": {
    team: "ATL",
    pos: "RB",
    adp: 2,
    proj: 346,
    dsValue: 95,
    tags: ["elite"],
    note: "Safest RB workload. DS injury risk is the lowest of the elite backs.",
  },
  "Christian McCaffrey": {
    team: "SF",
    pos: "RB",
    adp: 5,
    proj: 331,
    dsValue: 89,
    injury: "watch",
    tags: ["elite", "ds-boost"],
    note: "DS still has him PPR #5 with a 78% injury-risk flag. Ceiling is league-winning; plan a handcuff.",
  },
  "Jaxon Smith-Njigba": {
    team: "SEA",
    pos: "WR",
    adp: 8,
    proj: 315,
    dsValue: 84,
    tags: ["elite"],
    note: "Kickoff-game WR1 for the Super Bowl champs. FP has him ahead of ADP.",
  },
  "Amon-Ra St. Brown": {
    team: "DET",
    pos: "WR",
    adp: 11,
    proj: 316,
    dsValue: 82,
    tags: ["elite"],
    note: "Target hog next to Gibbs. The most boring elite WR — that's a compliment.",
  },
  "CeeDee Lamb": {
    team: "DAL",
    pos: "WR",
    adp: 13,
    proj: 301,
    dsValue: 75,
    tags: ["elite"],
  },
  "Justin Jefferson": {
    team: "MIN",
    pos: "WR",
    adp: 14,
    proj: 292,
    dsValue: 74,
    tags: ["elite", "ds-boost"],
    note: "DS still has him inside the top 10. ADP has cooled — that's the buy.",
  },
  "Jonathan Taylor": {
    team: "IND",
    pos: "RB",
    adp: 4,
    proj: 299,
    dsValue: 70,
    tags: ["fp-boost"],
    note: "FP ranks him well above DS. Don't reach past Gibbs/Bijan/Chase/Nacua for him.",
  },
  "James Cook III": {
    team: "BUF",
    pos: "RB",
    adp: 9,
    proj: 296,
    dsValue: 69,
    tags: ["elite"],
  },
  "Kenneth Walker III": {
    team: "KC",
    pos: "RB",
    adp: 17,
    proj: 279,
    dsValue: 62,
    tags: ["ds-boost", "situation"],
    note: "New Chiefs lead back. Biggest round-2 gap: DS 12 vs FP ~19. Smash if he lasts.",
  },
  "Drake London": {
    team: "ATL",
    pos: "WR",
    adp: 22,
    proj: 273,
    dsValue: 61,
    tags: ["value"],
    note: "FP ECR vs ADP is a plus-5. Target in the late 2nd / early 3rd.",
  },
  "A.J. Brown": {
    team: "NE",
    pos: "WR",
    adp: 18,
    proj: 272,
    dsValue: 60,
    tags: ["situation", "value"],
    note: "Patriots trade, McDaniels alpha role, Drake Maye. FP experts have him 6 spots above ADP.",
  },
  "Saquon Barkley": {
    team: "PHI",
    pos: "RB",
    adp: 12,
    proj: 270,
    dsValue: 60,
  },
  "Nico Collins": {
    team: "HOU",
    pos: "WR",
    adp: 24,
    proj: 269,
    dsValue: 58,
    tags: ["value"],
  },
  "De'Von Achane": {
    team: "MIA",
    pos: "RB",
    adp: 12,
    proj: 272,
    dsValue: 58,
    injury: "watch",
    tags: ["volatile"],
    note: "Going late first (DS ADP 1.12) with a high injury %. Fine if you already have a sturdy RB1.",
  },
  "Chase Brown": {
    team: "CIN",
    pos: "RB",
    adp: 13,
    proj: 267,
    dsValue: 56,
    tags: ["fp-boost"],
    note: "FP has him a full round ahead of DraftSharks. Don't panic-reach if Walker/Hampton are there.",
  },
  "Ashton Jeanty": {
    team: "LV",
    pos: "RB",
    adp: 15,
    proj: 262,
    dsValue: 56,
    injury: "watch",
    tags: ["volatile"],
    note: "Preseason leg injury. Sporting News dropped him 15→24. Discount is real — so is the workload if he's healthy.",
  },
  "Rashee Rice": {
    team: "KC",
    pos: "WR",
    adp: 29,
    proj: 268,
    dsValue: 55,
    tags: ["ds-boost", "value"],
    note: "DS 3D #20 with a 3.05 ADP. That's the kind of WR you let fall into the 3rd.",
  },
  "George Pickens": {
    team: "DAL",
    pos: "WR",
    adp: 23,
    proj: 262,
    dsValue: 55,
    tags: ["volatile"],
  },
  "Omarion Hampton": {
    team: "LAC",
    pos: "RB",
    adp: 16,
    proj: 260,
    dsValue: 55,
  },
  "Brock Bowers": {
    team: "LV",
    pos: "TE",
    adp: 21,
    proj: 259,
    dsValue: 53,
    injury: "watch",
    tags: ["elite", "fp-boost"],
    note: "Only TE worth a 2nd. FP likes him more than DS. If you're pick 1 or 2, he may be gone at the 3/4 turn.",
  },
  "Josh Allen": {
    team: "BUF",
    pos: "QB",
    adp: 36,
    proj: 376,
    dsValue: 52,
    tags: ["elite", "ds-boost"],
    note: "DS overall #24. In 1QB, that's a mild reach; in Superflex he's a top-8 pick. Wait unless the board is barren.",
  },
  "Derrick Henry": {
    team: "BAL",
    pos: "RB",
    adp: 10,
    proj: 263,
    dsValue: 51,
    tags: ["age-risk"],
    note: "ADP is ahead of both ranking sets. Let someone else pay the 1.10 tax.",
  },
  "Trey McBride": {
    team: "ARI",
    pos: "TE",
    adp: 28,
    proj: 248,
    tags: ["elite"],
    note: "TE1 last year. If Bowers goes, McBride is the last true difference-maker at the position.",
  },
  "DeVonta Smith": { team: "PHI", pos: "WR", adp: 32, proj: 242 },
  "Josh Jacobs": { team: "GB", pos: "RB", adp: 31, proj: 238 },
  "Ladd McConkey": { team: "LAC", pos: "WR", adp: 40, proj: 241 },
  "Tee Higgins": { team: "CIN", pos: "WR", adp: 38, proj: 243 },
  "Zay Flowers": { team: "BAL", pos: "WR", adp: 34, proj: 243 },
  "Malik Nabers": {
    team: "NYG",
    pos: "WR",
    adp: 30,
    proj: 236,
    injury: "watch",
    tags: ["volatile"],
    note: "ACL/meniscus rehab. Progress is good; Week 1 workload is not. Don't draft him as your WR1.",
  },
  "Kyren Williams": { team: "LAR", pos: "RB", adp: 27, proj: 236 },
  "Javonte Williams": { team: "DAL", pos: "RB", adp: 33, proj: 247 },
  "Tetairoa McMillan": { team: "CAR", pos: "WR", adp: 37, proj: 241 },
  "Lamar Jackson": {
    team: "BAL",
    pos: "QB",
    adp: 47,
    proj: 345,
    tags: ["elite"],
    note: "Wait until the 4th/5th in 1QB. Superflex: he's a 2nd-rounder.",
  },
  "Jaylen Waddle": {
    team: "DEN",
    pos: "WR",
    adp: 39,
    proj: 243,
    tags: ["situation"],
    note: "New Broncos WR1. Volume should bounce back next to Bo Nix.",
  },
  "Garrett Wilson": { team: "NYJ", pos: "WR", adp: 41, proj: 241 },
  "Jeremiyah Love": {
    team: "ARI",
    pos: "RB",
    adp: 26,
    proj: 255,
    injury: "watch",
    note: "High ankle in preseason. Talent is 2nd-round; confirm he's practicing before you pay that.",
  },
  "Tyler Warren": {
    team: "IND",
    pos: "TE",
    adp: 48,
    proj: 199,
    injury: "watch",
    note: "Groin scare. Still the TE3/4 range if healthy — have a backup name ready.",
  },
  "Colston Loveland": {
    team: "CHI",
    pos: "TE",
    adp: 42,
    proj: 230,
    tags: ["breakout"],
    note: "The TE you take if you miss Bowers/McBride and don't want to stream.",
  },
  "Breece Hall": { team: "NYJ", pos: "RB", adp: 35, proj: 236 },
  "Travis Etienne Jr.": { team: "NO", pos: "RB", adp: 46, proj: 247 },
  "Chris Olave": { team: "NO", pos: "WR", adp: 44, proj: 255, tags: ["value"] },
  "Bucky Irving": { team: "TB", pos: "RB", adp: 43, proj: 211 },
  "Drake Maye": {
    team: "NE",
    pos: "QB",
    adp: 53,
    proj: 300,
    tags: ["breakout"],
    note: "DS-style build: take Maye a round after Allen/Lamar, not instead of a WR2.",
  },
  "Jayden Daniels": { team: "WAS", pos: "QB", adp: 54, proj: 299 },
  "Rome Odunze": {
    team: "CHI",
    pos: "WR",
    adp: 52,
    proj: 224,
    tags: ["value"],
    note: "Quietly the Bears' most physical WR. Burden/Loveland hype is burying him a round too far.",
  },
  "Terry McLaurin": { team: "WAS", pos: "WR", adp: 49, proj: 241 },
  "Emeka Egbuka": {
    team: "TB",
    pos: "WR",
    adp: 50,
    proj: 241,
    injury: "questionable",
    note: "Toe — missing practice, Week 1 not secure. Have a replacement if you draft him.",
  },
  "Luther Burden III": {
    team: "CHI",
    pos: "WR",
    adp: 55,
    proj: 241,
    injury: "watch",
    note: "Back from a groin but still limited. Don't stack three Bears pass-catchers.",
  },
  "Jalen Hurts": { team: "PHI", pos: "QB", adp: 58, proj: 298 },
  "Mike Evans": { team: "SF", pos: "WR", adp: 57, proj: 199 },
  "Davante Adams": { team: "LAR", pos: "WR", adp: 56, proj: 206 },
  "Bhayshul Tuten": { team: "JAX", pos: "RB", adp: 62, proj: 218 },
  "D'Andre Swift": { team: "CHI", pos: "RB", adp: 60, proj: 236 },
  "Christian Watson": { team: "GB", pos: "WR", adp: 61, proj: 224 },
  "Parker Washington": {
    team: "JAX",
    pos: "WR",
    adp: 64,
    proj: 224,
    tags: ["sleeper"],
  },
  "Jameson Williams": { team: "DET", pos: "WR", adp: 63, proj: 224 },
  "David Montgomery": { team: "HOU", pos: "RB", adp: 65, proj: 218 },
  "TreVeyon Henderson": { team: "NE", pos: "RB", adp: 68, proj: 202 },
  "Jadarian Price": { team: "SEA", pos: "RB", adp: 66, proj: 211 },
  "Tony Pollard": { team: "TEN", pos: "RB", adp: 70, proj: 179 },
  "Kyle Pitts Sr.": { team: "ATL", pos: "TE", adp: 72, proj: 179 },
  "Michael Pittman Jr.": { team: "PIT", pos: "WR", adp: 74, proj: 199 },
  "Marvin Harrison Jr.": { team: "ARI", pos: "WR", adp: 69, proj: 206 },
  "Harold Fannin Jr.": { team: "CLE", pos: "TE", adp: 71, proj: 179 },
  "DK Metcalf": { team: "PIT", pos: "WR", adp: 73, proj: 206 },
  "Sam LaPorta": {
    team: "DET",
    pos: "TE",
    adp: 76,
    proj: 192,
    injury: "watch",
    note: "Hip issue in camp. Still a TE1 if he's practicing by Wednesday.",
  },
  "Joe Burrow": { team: "CIN", pos: "QB", adp: 75, proj: 326 },
  "Jaxson Dart": {
    team: "NYG",
    pos: "QB",
    adp: 78,
    proj: 308,
    tags: ["sleeper"],
    note: "Late-round QB with rushing juice. Fine as your QB1 in 1QB if Allen/Maye/Lamar are gone.",
  },
  "Courtland Sutton": { team: "DEN", pos: "WR", adp: 79, proj: 173 },
  "Michael Wilson": { team: "ARI", pos: "WR", adp: 80, proj: 175 },
  "Trevor Lawrence": { team: "JAX", pos: "QB", adp: 81, proj: 301 },
  "Rhamondre Stevenson": { team: "NE", pos: "RB", adp: 82, proj: 202 },
  "Jonathon Brooks": { team: "CAR", pos: "RB", adp: 83, proj: 179 },
  "Caleb Williams": { team: "CHI", pos: "QB", adp: 84, proj: 311 },
  "Dak Prescott": { team: "DAL", pos: "QB", adp: 85, proj: 301 },
  "Bo Nix": { team: "DEN", pos: "QB", adp: 86, proj: 274 },
  "Brock Purdy": { team: "SF", pos: "QB", adp: 87, proj: 269 },
  "Matthew Stafford": { team: "LAR", pos: "QB", adp: 88, proj: 264 },
  "Matthew Golden": {
    team: "GB",
    pos: "WR",
    adp: 90,
    proj: 143,
    tags: ["sleeper"],
  },
  "Brian Thomas Jr.": { team: "JAX", pos: "WR", adp: 89, proj: 199 },
  "Justin Herbert": { team: "LAC", pos: "QB", adp: 91, proj: 311 },
  "Jakobi Meyers": { team: "JAX", pos: "WR", adp: 92, proj: 199 },
  "Jordan Addison": { team: "MIN", pos: "WR", adp: 93, proj: 167 },
  "Alec Pierce": { team: "IND", pos: "WR", adp: 94, proj: 167 },
  "Josh Downs": { team: "IND", pos: "WR", adp: 95, proj: 206 },
  "Makai Lemon": { team: "PHI", pos: "WR", adp: 96, proj: 173 },
  "Patrick Mahomes": {
    team: "KC",
    pos: "QB",
    adp: 97,
    proj: 274,
    injury: "watch",
    note: "Cautious early-season usage possible. Still a fine QB2/late QB1.",
  },
  "Jaylen Warren": { team: "PIT", pos: "RB", adp: 98, proj: 202 },
  "J.K. Dobbins": { team: "DEN", pos: "RB", adp: 99, proj: 148 },
  "Kenny Gainwell": { team: "TB", pos: "RB", adp: 100, proj: 179 },
  "Rico Dowdle": { team: "PIT", pos: "RB", adp: 101, proj: 179 },
  "Chuba Hubbard": { team: "CAR", pos: "RB", adp: 102, proj: 197 },
  "Wan'Dale Robinson": { team: "TEN", pos: "WR", adp: 103, proj: 177 },
  "Rachaad White": { team: "WAS", pos: "RB", adp: 104, proj: 158 },
  "Dallas Goedert": { team: "PHI", pos: "TE", adp: 105, proj: 163 },
  "Travis Kelce": { team: "KC", pos: "TE", adp: 106, proj: 163 },
  "RJ Harvey": { team: "DEN", pos: "RB", adp: 107, proj: 148 },
  "Blake Corum": { team: "LAR", pos: "RB", adp: 108, proj: 179 },
  "Kyler Murray": { team: "MIN", pos: "QB", adp: 109, proj: 264 },
  "Jayden Reed": { team: "GB", pos: "WR", adp: 110, proj: 199 },
  "Dalton Kincaid": { team: "BUF", pos: "TE", adp: 111, proj: 179 },
  "Jake Ferguson": { team: "DAL", pos: "TE", adp: 112, proj: 179 },
  "Mark Andrews": { team: "BAL", pos: "TE", adp: 113, proj: 141 },
  "T.J. Hockenson": { team: "MIN", pos: "TE", adp: 114, proj: 141 },
  "Aaron Jones Sr.": { team: "MIN", pos: "RB", adp: 115, proj: 148 },
  "KC Concepcion": {
    team: "CLE",
    pos: "WR",
    adp: 116,
    proj: 167,
    tags: ["sleeper"],
  },
  "Jacory Croskey-Merritt": { team: "WAS", pos: "RB", adp: 117, proj: 179 },
  "Isaiah Likely": { team: "NYG", pos: "TE", adp: 118, proj: 179 },
  "Jalen Coker": { team: "CAR", pos: "WR", adp: 119, proj: 143 },
  "Tucker Kraft": {
    team: "GB",
    pos: "TE",
    adp: 77,
    proj: 218,
    injury: "watch",
    tags: ["sleeper"],
    note: "Back in team drills after ACL. If he's practicing, this ADP is a gift.",
  },
  "Quentin Johnston": { team: "LAC", pos: "WR", adp: 121, proj: 199 },
  "Romeo Doubs": { team: "NE", pos: "WR", adp: 122, proj: 167 },
  "Stefon Diggs": { team: "WAS", pos: "WR", adp: 123, proj: 199 },
  "Hunter Henry": { team: "NE", pos: "TE", adp: 124, proj: 141 },
  "Kyle Monangai": { team: "CHI", pos: "RB", adp: 125, proj: 168 },
  "Tyler Shough": { team: "NO", pos: "QB", adp: 126, proj: 248 },
  "Deebo Samuel Sr.": { team: "SF", pos: "WR", adp: 127, proj: 143 },
  "Woody Marks": { team: "HOU", pos: "RB", adp: 128, proj: 128 },
  "Xavier Worthy": { team: "KC", pos: "WR", adp: 129, proj: 167 },
  "Khalil Shakir": { team: "BUF", pos: "WR", adp: 130, proj: 173 },
  "George Kittle": { team: "SF", pos: "TE", adp: 131, proj: 192 },
  "Tank Bigsby": { team: "PHI", pos: "RB", adp: 132, proj: 116 },
  "Chris Godwin Jr.": { team: "TB", pos: "WR", adp: 133, proj: 173 },
  "Jerry Jeudy": { team: "CLE", pos: "WR", adp: 134, proj: 143 },
  "Jared Goff": { team: "DET", pos: "QB", adp: 135, proj: 264 },
  "Jordan Mason": { team: "MIN", pos: "RB", adp: 136, proj: 168 },
  "Daniel Jones": { team: "IND", pos: "QB", adp: 137, proj: 235 },
  "Rashid Shaheed": { team: "SEA", pos: "WR", adp: 138, proj: 167 },
  "Alvin Kamara": {
    team: "NO",
    pos: "RB",
    adp: 140,
    proj: 116,
    injury: "out",
    note: "Out at least a month. Only a stash in deep benches.",
  },
  "Chris Rodriguez Jr.": {
    team: "JAX",
    pos: "RB",
    adp: 139,
    proj: 148,
    tags: ["sleeper"],
  },
  "Brian Robinson Jr.": { team: "ATL", pos: "RB", adp: 141, proj: 111 },
  "Baker Mayfield": { team: "TB", pos: "QB", adp: 142, proj: 238 },
  "Isiah Pacheco": { team: "DET", pos: "RB", adp: 143, proj: 116 },
  "Malik Willis": { team: "MIA", pos: "QB", adp: 144, proj: 248 },
  "Calvin Ridley": { team: "TEN", pos: "WR", adp: 145, proj: 121 },
  "Denzel Boston": { team: "CLE", pos: "WR", adp: 146, proj: 133 },
  "Travis Hunter": { team: "JAX", pos: "WR", adp: 147, proj: 143 },
  "Adonai Mitchell": { team: "NYJ", pos: "WR", adp: 148, proj: 133 },
  "Kenyon Sadiq": { team: "NYJ", pos: "TE", adp: 149, proj: 136 },
  "Jalen Nailor": { team: "LV", pos: "WR", adp: 150, proj: 133 },
  "Tre Tucker": { team: "LV", pos: "WR", adp: 151, proj: 143 },
  "Ray Davis": { team: "BUF", pos: "RB", adp: 152, proj: 105 },
  "Tyrone Tracy Jr.": { team: "NYG", pos: "RB", adp: 153, proj: 102 },
  "Mike Washington Jr.": { team: "LV", pos: "RB", adp: 154, proj: 116 },
  "Juwan Johnson": { team: "NO", pos: "TE", adp: 155, proj: 179 },
  "Tyler Allgeier": { team: "ARI", pos: "RB", adp: 156, proj: 128 },
  "Keaton Mitchell": { team: "LAC", pos: "RB", adp: 157, proj: 128 },
  "Dylan Sampson": { team: "CLE", pos: "RB", adp: 158, proj: 116 },
  "Terrance Ferguson": { team: "LAR", pos: "TE", adp: 159, proj: 120 },
  "Rashod Bateman": { team: "BAL", pos: "WR", adp: 160, proj: 121 },
  "Jauan Jennings": { team: "MIN", pos: "WR", adp: 161, proj: 134 },
  "Tyjae Spears": { team: "TEN", pos: "RB", adp: 162, proj: 116 },
  "Jordan Love": { team: "GB", pos: "QB", adp: 163, proj: 269 },
  "Jalen McMillan": { team: "TB", pos: "WR", adp: 164, proj: 143 },
  "Braelon Allen": { team: "NYJ", pos: "RB", adp: 165, proj: 100 },
  "Zach Charbonnet": {
    team: "SEA",
    pos: "RB",
    adp: 177,
    proj: 148,
    injury: "out",
    note: "ACL — miss at least Weeks 1-4. Only a handcuff stash.",
  },
  "MarShawn Lloyd": {
    team: "GB",
    pos: "RB",
    adp: 166,
    proj: 179,
    tags: ["sleeper"],
    note: "Packers RB committee dart. Worth a late pick if Jacobs' efficiency dips.",
  },
  "Carnell Tate": { team: "TEN", pos: "WR", adp: 51, proj: 206, tags: ["sleeper"] },
  "Quinshon Judkins": { team: "CLE", pos: "RB", adp: 59, proj: 218 },
  "Cam Skattebo": {
    team: "NYG",
    pos: "RB",
    adp: 45,
    proj: 223,
    tags: ["breakout"],
    note: "Harbaugh workhorse label. Reckless runner, but RB1 upside in the 4th.",
  },
  "Jordyn Tyson": {
    team: "NO",
    pos: "WR",
    adp: 180,
    proj: 167,
    injury: "out",
    note: "Hamstring, ~2 months. Skip in redraft unless you have an IR spot.",
  },
  "Keenan Allen": { team: "IND", pos: "WR", adp: 168, proj: 134 },
  "Cooper Kupp": { team: "SEA", pos: "WR", adp: 169, proj: 112 },
  "Kayshon Boutte": { team: "HOU", pos: "WR", adp: 170, proj: 126 },
  "Tank Dell": { team: "HOU", pos: "WR", adp: 171, proj: 121 },
  "Brenton Strange": { team: "JAX", pos: "TE", adp: 172, proj: 141 },
  "Dalton Schultz": { team: "HOU", pos: "TE", adp: 173, proj: 141 },
  "Chig Okonkwo": { team: "WAS", pos: "TE", adp: 174, proj: 141 },
  "Pat Freiermuth": { team: "PIT", pos: "TE", adp: 175, proj: 120 },
  "Oronde Gadsden": { team: "LAC", pos: "TE", adp: 176, proj: 120 },
  "C.J. Stroud": { team: "HOU", pos: "QB", adp: 178, proj: 235 },
  "Sam Darnold": { team: "SEA", pos: "QB", adp: 179, proj: 220 },
  "Cam Ward": { team: "TEN", pos: "QB", adp: 181, proj: 210 },
  "Bryce Young": { team: "CAR", pos: "QB", adp: 182, proj: 205 },
  "Fernando Mendoza": { team: "LV", pos: "QB", adp: 183, proj: 205 },
  "Ryan Flournoy": { team: "DAL", pos: "WR", adp: 184, proj: 134 },
  "Dontayvion Wicks": { team: "PHI", pos: "WR", adp: 185, proj: 133 },
  "Isaac TeSlaa": { team: "DET", pos: "WR", adp: 186, proj: 121 },
  "Jaylin Noel": { team: "HOU", pos: "WR", adp: 187, proj: 126 },
  "Tre Harris": { team: "LAC", pos: "WR", adp: 188, proj: 133 },
  "Keon Coleman": {
    team: "BUF",
    pos: "WR",
    adp: 189,
    proj: 118,
    injury: "watch",
    note: "Sprained foot/toe in preseason. Monitor before a dart throw.",
  },
  "Jonah Coleman": { team: "DEN", pos: "RB", adp: 190, proj: 116 },
  "Kimani Vidal": { team: "LAC", pos: "RB", adp: 191, proj: 111 },
  "Jaydon Blue": { team: "DAL", pos: "RB", adp: 192, proj: 100 },
  "Sean Tucker": { team: "TB", pos: "RB", adp: 193, proj: 111 },
  "AJ Barner": { team: "SEA", pos: "TE", adp: 194, proj: 136 },
  "Cade Otton": { team: "TB", pos: "TE", adp: 195, proj: 118 },
  "Evan Engram": { team: "DEN", pos: "TE", adp: 196, proj: 118 },
  "James Conner": { team: "ARI", pos: "RB", adp: 197, proj: 95 },
  "Justice Hill": { team: "BAL", pos: "RB", adp: 198, proj: 90 },
  "DJ Giddens": { team: "IND", pos: "RB", adp: 199, proj: 95 },
  "Emmett Johnson": { team: "KC", pos: "RB", adp: 200, proj: 90 },
  "Brandon Aubrey": { team: "DAL", pos: "K", adp: 178, proj: 155 },
  "Cameron Dicker": { team: "LAC", pos: "K", adp: 182, proj: 148 },
  "Jason Myers": { team: "SEA", pos: "K", adp: 186, proj: 142 },
  "Harrison Mevis": { team: "LAR", pos: "K", adp: 190, proj: 140 },
  "Ka'imi Fairbairn": { team: "HOU", pos: "K", adp: 194, proj: 138 },
  "Eddy Pineiro": { team: "SF", pos: "K", adp: 198, proj: 136 },
  "Harrison Butker": { team: "KC", pos: "K", adp: 202, proj: 134 },
  "Jake Bates": { team: "DET", pos: "K", adp: 206, proj: 132 },
  "Chris Boswell": { team: "PIT", pos: "K", adp: 210, proj: 130 },
  "Chase McLaughlin": { team: "TB", pos: "K", adp: 214, proj: 128 },
  "Cam Little": { team: "JAX", pos: "K", adp: 218, proj: 126 },
  "Evan McPherson": { team: "CIN", pos: "K", adp: 222, proj: 124 },
  "Broncos": { team: "DEN", pos: "DST", adp: 165, proj: 128 },
  "Texans": { team: "HOU", pos: "DST", adp: 168, proj: 126 },
  "Steelers": { team: "PIT", pos: "DST", adp: 172, proj: 124 },
  "Seahawks": { team: "SEA", pos: "DST", adp: 176, proj: 122 },
  "Rams": { team: "LAR", pos: "DST", adp: 180, proj: 120 },
  "Ravens": { team: "BAL", pos: "DST", adp: 184, proj: 118 },
  "Eagles": { team: "PHI", pos: "DST", adp: 188, proj: 116 },
  "Browns": { team: "CLE", pos: "DST", adp: 192, proj: 114 },
  "Patriots": { team: "NE", pos: "DST", adp: 196, proj: 112 },
  "Lions": { team: "DET", pos: "DST", adp: 200, proj: 110 },
  "Chiefs": { team: "KC", pos: "DST", adp: 204, proj: 108 },
  "Chargers": { team: "LAC", pos: "DST", adp: 208, proj: 106 },
  "Buccaneers": { team: "TB", pos: "DST", adp: 212, proj: 104 },
  "Packers": { team: "GB", pos: "DST", adp: 216, proj: 102 },
  "Jaguars": { team: "JAX", pos: "DST", adp: 220, proj: 100 },
  "Colts": { team: "IND", pos: "DST", adp: 224, proj: 98 },
};

/** FantasyPros-style PPR ECR order, Sept 1 2026. */
const FP_ORDER = [
  "Ja'Marr Chase",
  "Jahmyr Gibbs",
  "Puka Nacua",
  "Bijan Robinson",
  "Jaxon Smith-Njigba",
  "Amon-Ra St. Brown",
  "Jonathan Taylor",
  "Christian McCaffrey",
  "CeeDee Lamb",
  "James Cook III",
  "Justin Jefferson",
  "Chase Brown",
  "Drake London",
  "A.J. Brown",
  "Saquon Barkley",
  "De'Von Achane",
  "Brock Bowers",
  "Ashton Jeanty",
  "Kenneth Walker III",
  "Nico Collins",
  "Derrick Henry",
  "Omarion Hampton",
  "Trey McBride",
  "George Pickens",
  "Rashee Rice",
  "Kyren Williams",
  "Josh Jacobs",
  "Malik Nabers",
  "DeVonta Smith",
  "Jeremiyah Love",
  "Zay Flowers",
  "Breece Hall",
  "Javonte Williams",
  "Tee Higgins",
  "Ladd McConkey",
  "Josh Allen",
  "Tetairoa McMillan",
  "Garrett Wilson",
  "Jaylen Waddle",
  "Bucky Irving",
  "Chris Olave",
  "Tyler Warren",
  "Colston Loveland",
  "Travis Etienne Jr.",
  "Rome Odunze",
  "Terry McLaurin",
  "Lamar Jackson",
  "Jayden Daniels",
  "Cam Skattebo",
  "Emeka Egbuka",
  "Quinshon Judkins",
  "Carnell Tate",
  "Drake Maye",
  "Luther Burden III",
  "Jalen Hurts",
  "Mike Evans",
  "Davante Adams",
  "Bhayshul Tuten",
  "D'Andre Swift",
  "Christian Watson",
  "Parker Washington",
  "Jameson Williams",
  "David Montgomery",
  "TreVeyon Henderson",
  "Jadarian Price",
  "Tony Pollard",
  "Kyle Pitts Sr.",
  "Michael Pittman Jr.",
  "Marvin Harrison Jr.",
  "Harold Fannin Jr.",
  "DK Metcalf",
  "Sam LaPorta",
  "Joe Burrow",
  "Jaxson Dart",
  "Courtland Sutton",
  "Michael Wilson",
  "Trevor Lawrence",
  "Rhamondre Stevenson",
  "Jonathon Brooks",
  "Tucker Kraft",
  "Caleb Williams",
  "Dak Prescott",
  "Bo Nix",
  "Brock Purdy",
  "Matthew Stafford",
  "Matthew Golden",
  "Brian Thomas Jr.",
  "Justin Herbert",
  "Jakobi Meyers",
  "Jordan Addison",
  "Alec Pierce",
  "Josh Downs",
  "Makai Lemon",
  "Patrick Mahomes",
  "Jaylen Warren",
  "J.K. Dobbins",
  "Kenny Gainwell",
  "Rico Dowdle",
  "Chuba Hubbard",
  "Wan'Dale Robinson",
  "Rachaad White",
  "Dallas Goedert",
  "Travis Kelce",
  "RJ Harvey",
  "Blake Corum",
  "Kyler Murray",
  "Jayden Reed",
  "Dalton Kincaid",
  "Jake Ferguson",
  "Mark Andrews",
  "T.J. Hockenson",
  "Aaron Jones Sr.",
  "KC Concepcion",
  "Jacory Croskey-Merritt",
  "Isaiah Likely",
  "Jalen Coker",
  "Quentin Johnston",
  "Romeo Doubs",
  "Stefon Diggs",
  "Hunter Henry",
  "Kyle Monangai",
  "Tyler Shough",
  "Deebo Samuel Sr.",
  "Woody Marks",
  "Xavier Worthy",
  "Khalil Shakir",
  "George Kittle",
  "Tank Bigsby",
  "Chris Godwin Jr.",
  "Jerry Jeudy",
  "Jared Goff",
  "Jordan Mason",
  "Daniel Jones",
  "Rashid Shaheed",
  "Chris Rodriguez Jr.",
  "Alvin Kamara",
  "Brian Robinson Jr.",
  "Baker Mayfield",
  "Isiah Pacheco",
  "Malik Willis",
  "Calvin Ridley",
  "Denzel Boston",
  "Travis Hunter",
  "Adonai Mitchell",
  "Kenyon Sadiq",
  "Jalen Nailor",
  "Tre Tucker",
  "Ray Davis",
  "Tyrone Tracy Jr.",
  "Mike Washington Jr.",
  "Juwan Johnson",
  "Tyler Allgeier",
  "Keaton Mitchell",
  "Dylan Sampson",
  "Terrance Ferguson",
  "Rashod Bateman",
  "Jauan Jennings",
  "Tyjae Spears",
  "Jordan Love",
  "Jalen McMillan",
  "Braelon Allen",
  "MarShawn Lloyd",
  "Zach Charbonnet",
  "Keenan Allen",
  "Cooper Kupp",
  "Kayshon Boutte",
  "Tank Dell",
  "Brenton Strange",
  "Dalton Schultz",
  "Chig Okonkwo",
  "Pat Freiermuth",
  "Oronde Gadsden",
  "C.J. Stroud",
  "Sam Darnold",
  "Cam Ward",
  "Bryce Young",
  "Fernando Mendoza",
  "Ryan Flournoy",
  "Dontayvion Wicks",
  "Isaac TeSlaa",
  "Jaylin Noel",
  "Tre Harris",
  "Keon Coleman",
  "Jonah Coleman",
  "Kimani Vidal",
  "Jaydon Blue",
  "Sean Tucker",
  "AJ Barner",
  "Cade Otton",
  "Evan Engram",
  "James Conner",
  "Justice Hill",
  "DJ Giddens",
  "Emmett Johnson",
  "Jordyn Tyson",
  "Broncos",
  "Texans",
  "Steelers",
  "Seahawks",
  "Rams",
  "Ravens",
  "Eagles",
  "Browns",
  "Patriots",
  "Lions",
  "Chiefs",
  "Chargers",
  "Buccaneers",
  "Packers",
  "Jaguars",
  "Colts",
  "Brandon Aubrey",
  "Cameron Dicker",
  "Jason Myers",
  "Harrison Mevis",
  "Ka'imi Fairbairn",
  "Eddy Pineiro",
  "Harrison Butker",
  "Jake Bates",
  "Chris Boswell",
  "Chase McLaughlin",
  "Cam Little",
  "Evan McPherson",
];

/** DraftSharks PPR 3D order. Top 25 from DS Sept 1; remainder projection-styled. */
const DS_ORDER = [
  "Jahmyr Gibbs",
  "Puka Nacua",
  "Ja'Marr Chase",
  "Bijan Robinson",
  "Christian McCaffrey",
  "Jaxon Smith-Njigba",
  "Amon-Ra St. Brown",
  "CeeDee Lamb",
  "Justin Jefferson",
  "Jonathan Taylor",
  "James Cook III",
  "Kenneth Walker III",
  "Drake London",
  "A.J. Brown",
  "Saquon Barkley",
  "Nico Collins",
  "De'Von Achane",
  "Chase Brown",
  "Ashton Jeanty",
  "Rashee Rice",
  "George Pickens",
  "Omarion Hampton",
  "Brock Bowers",
  "Josh Allen",
  "Derrick Henry",
  "Trey McBride",
  "Ladd McConkey",
  "Tee Higgins",
  "DeVonta Smith",
  "Josh Jacobs",
  "Zay Flowers",
  "Kyren Williams",
  "Javonte Williams",
  "Tetairoa McMillan",
  "Chris Olave",
  "Jaylen Waddle",
  "Garrett Wilson",
  "Lamar Jackson",
  "Malik Nabers",
  "Breece Hall",
  "Colston Loveland",
  "Tyler Warren",
  "Jeremiyah Love",
  "Drake Maye",
  "Jayden Daniels",
  "Rome Odunze",
  "Terry McLaurin",
  "Bucky Irving",
  "Travis Etienne Jr.",
  "Davante Adams",
  "Jameson Williams",
  "Christian Watson",
  "D'Andre Swift",
  "Cam Skattebo",
  "Carnell Tate",
  "Parker Washington",
  "Jalen Hurts",
  "Joe Burrow",
  "Quinshon Judkins",
  "David Montgomery",
  "Marvin Harrison Jr.",
  "Tucker Kraft",
  "Bhayshul Tuten",
  "Jadarian Price",
  "DK Metcalf",
  "TreVeyon Henderson",
  "Sam LaPorta",
  "Josh Downs",
  "Brian Thomas Jr.",
  "Luther Burden III",
  "Emeka Egbuka",
  "Mike Evans",
  "Jaylen Warren",
  "Rhamondre Stevenson",
  "Justin Herbert",
  "Jaxson Dart",
  "Caleb Williams",
  "Harold Fannin Jr.",
  "Michael Pittman Jr.",
  "Tony Pollard",
  "Stefon Diggs",
  "Kenny Gainwell",
  "Jakobi Meyers",
  "Trevor Lawrence",
  "Jonathon Brooks",
  "Michael Wilson",
  "Courtland Sutton",
  "Kyle Pitts Sr.",
  "Khalil Shakir",
  "Jacory Croskey-Merritt",
  "Makai Lemon",
  "Rico Dowdle",
  "Dak Prescott",
  "Bo Nix",
  "Matthew Golden",
  "Dalton Kincaid",
  "Jordan Addison",
  "Jordan Mason",
  "Rashid Shaheed",
  "Romeo Doubs",
  "Patrick Mahomes",
  "Isaiah Likely",
  "Brock Purdy",
  "Kyle Monangai",
  "Alec Pierce",
  "KC Concepcion",
  "Xavier Worthy",
  "Rachaad White",
  "George Kittle",
  "Juwan Johnson",
  "Matthew Stafford",
  "Jake Ferguson",
  "Jordan Love",
  "J.K. Dobbins",
  "Deebo Samuel Sr.",
  "RJ Harvey",
  "Jalen Coker",
  "Tre Tucker",
  "Chris Rodriguez Jr.",
  "Dallas Goedert",
  "Travis Hunter",
  "Travis Kelce",
  "Aaron Jones Sr.",
  "Jalen McMillan",
  "Kyler Murray",
  "Chuba Hubbard",
  "Wan'Dale Robinson",
  "Jayden Reed",
  "Quentin Johnston",
  "Blake Corum",
  "Mark Andrews",
  "Woody Marks",
  "Chris Godwin Jr.",
  "Jerry Jeudy",
  "Chig Okonkwo",
  "Jared Goff",
  "Tyler Allgeier",
  "Keaton Mitchell",
  "Jauan Jennings",
  "Hunter Henry",
  "Jalen Nailor",
  "Tyler Shough",
  "Tre Harris",
  "Dontayvion Wicks",
  "Mike Washington Jr.",
  "Malik Willis",
  "Denzel Boston",
  "Brenton Strange",
  "Adonai Mitchell",
  "Isiah Pacheco",
  "Dalton Schultz",
  "Tank Bigsby",
  "Kayshon Boutte",
  "AJ Barner",
  "Baker Mayfield",
  "Tyjae Spears",
  "Dylan Sampson",
  "Rashod Bateman",
  "Daniel Jones",
  "Tank Dell",
  "Brian Robinson Jr.",
  "Calvin Ridley",
  "C.J. Stroud",
  "Cooper Kupp",
  "Keenan Allen",
  "Kimani Vidal",
  "Isaac TeSlaa",
  "Kenyon Sadiq",
  "MarShawn Lloyd",
  "Zach Charbonnet",
  "Alvin Kamara",
  "Ray Davis",
  "Tyrone Tracy Jr.",
  "Terrance Ferguson",
  "Braelon Allen",
  "T.J. Hockenson",
  "Pat Freiermuth",
  "Oronde Gadsden",
  "Sam Darnold",
  "Cam Ward",
  "Bryce Young",
  "Fernando Mendoza",
  "Ryan Flournoy",
  "Jaylin Noel",
  "Keon Coleman",
  "Jonah Coleman",
  "Jaydon Blue",
  "Sean Tucker",
  "Cade Otton",
  "Evan Engram",
  "James Conner",
  "Justice Hill",
  "DJ Giddens",
  "Emmett Johnson",
  "Jordyn Tyson",
  "Broncos",
  "Texans",
  "Steelers",
  "Seahawks",
  "Rams",
  "Ravens",
  "Eagles",
  "Browns",
  "Patriots",
  "Lions",
  "Chiefs",
  "Chargers",
  "Buccaneers",
  "Packers",
  "Jaguars",
  "Colts",
  "Brandon Aubrey",
  "Cameron Dicker",
  "Jason Myers",
  "Harrison Mevis",
  "Ka'imi Fairbairn",
  "Eddy Pineiro",
  "Harrison Butker",
  "Jake Bates",
  "Chris Boswell",
  "Chase McLaughlin",
  "Cam Little",
  "Evan McPherson",
];

function slug(name: string) {
  return name
    .toLowerCase()
    .replace(/['.]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function rankMap(order: string[]) {
  const map = new Map<string, number>();
  order.forEach((name, i) => map.set(name, i + 1));
  return map;
}

const fpMap = rankMap(FP_ORDER);
const dsMap = rankMap(DS_ORDER);

function buildPlayers(): Player[] {
  const names = new Set([...Object.keys(META), ...FP_ORDER, ...DS_ORDER]);
  const players: Player[] = [];
  for (const name of names) {
    const meta = META[name];
    if (!meta) continue;
    const fpRank = fpMap.get(name) ?? 999;
    const dsRank = dsMap.get(name) ?? 999;
    players.push({
      id: slug(name),
      name,
      team: meta.team,
      pos: meta.pos,
      bye: BYE_BY_TEAM[meta.team] ?? 0,
      fpRank,
      dsRank,
      adp: meta.adp,
      proj: meta.proj,
      dsValue: meta.dsValue,
      injury: meta.injury,
      note: meta.note,
      tags: meta.tags ?? [],
    });
  }
  return players;
}

export const PLAYERS: Player[] = buildPlayers();

export const PLAYER_BY_ID = new Map(PLAYERS.map((p) => [p.id, p]));

export function displayName(player: Player) {
  if (player.pos === "DST") return `${player.name} D/ST`;
  return player.name;
}
